apiVersion: v1
entries:
  stackbooster-agent:
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.8244879+03:00"
    dependencies:
    - alias: metricslite
      condition: metricslite.enabled
      name: metricslite
      repository: file://subcharts/metricslite
      version: 0.1.0
    - alias: metricsfull
      condition: metricsfull.enabled
      name: metricsfull
      repository: file://subcharts/metricsfull
      version: 0.1.0
    description: Stackbooster agent
    digest: 289171ac5c4087d20b4c9506e377f3f5768bc2b251876227d008b24c08336230
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.8089193+03:00"
    dependencies:
    - alias: metrics
      condition: metrics.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 27.16.0
    description: Stackbooster agent
    digest: 715671bf3058f752bc10d751c0bffd23e622a98f9551431a0dda9a197cb572c9
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.8024342+03:00"
    dependencies:
    - alias: metrics
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 27.16.0
    description: Stackbooster agent
    digest: 33e592da7bac9cae4ff6bdf1c5a27820b4dcdbd3a8cc183041c8ef2977dc9e69
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.795738+03:00"
    dependencies:
    - alias: metrics
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 27.16.0
    description: Stackbooster agent
    digest: e3bc258b72a4a736d031a87b7842f6a6d95b78553fd254e50822164b2ff24c7e
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.7881243+03:00"
    dependencies:
    - alias: metrics
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 27.16.0
    description: Stackbooster agent
    digest: c5525b71a8ea747cc73cf3c78cb4915bd8e997addcfc399aac7e8a90f0fb0e71
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.7801571+03:00"
    description: Stackbooster agent
    digest: 303325337f9568950ad4d8a6ea7fd669b1b99cb5bbf094fc7b335332e155c998
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.7791195+03:00"
    description: Stackbooster agent
    digest: 7d619e78cb9c1132282f09ec79d33f4d18126bb8051ba1a42f97c4ffde974e85
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.7781556+03:00"
    description: Stackbooster agent
    digest: 65e82d8cc40124f79e81141f55ee537644c60688efda726323af0d1cd9481159
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-08-20T13:44:29.7781556+03:00"
    description: Stackbooster agent
    digest: a715e5c9def603e20fc89b3c977cc5ab654af386af0cf60a3c06eccf25b388d5
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.0.tgz
    version: 1.0.0
generated: "2025-08-20T13:44:29.7768094+03:00"
