apiVersion: v1
entries:
  stackbooster-agent:
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-04-01T10:11:05.13424+07:00"
    description: Stackbooster agent
    digest: a715e5c9def603e20fc89b3c977cc5ab654af386af0cf60a3c06eccf25b388d5
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-1.0.0.tgz
    version: 1.0.0
generated: "2025-04-01T10:11:05.132658+07:00"
