apiVersion: v1
entries:
  stackbooster-agent:
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-03-25T09:16:57.611964+07:00"
    description: Stackbooster agent
    digest: 9420f49388aaf7ad7030b17ca8032b7f9cbdd68e56accb900b6bc7a280a022da
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2025-03-25T09:16:57.611209+07:00"
    description: Stackbooster agent
    digest: 0630b8550132e4612e8fc0b1eda10445fc51b231c717a4f26be789873771cd34
    icon: https://raw.githubusercontent.com/helm/helm/master/docs/images/logo-helm.svg
    name: stackbooster-agent
    type: application
    urls:
    - https://raw.githubusercontent.com/stackbooster/helm/main/charts/stackbooster-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-25T09:16:57.609946+07:00"
